# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [3]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [4]:
# your code here

np.__version__

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [17]:
# Method 1

a = np.random.random((2,3,5))
print(a)


[[[0.41562163 0.68989659 0.27424295 0.44820309 0.5785932 ]
  [0.53856533 0.46375266 0.20933654 0.47684804 0.17599704]
  [0.67101278 0.02383468 0.52006984 0.09654529 0.36597892]]

 [[0.80082229 0.81005922 0.59478441 0.50698579 0.22753137]
  [0.71910791 0.26076867 0.55518068 0.64886674 0.89072528]
  [0.79567356 0.76970088 0.07636264 0.70026583 0.67615485]]]


In [18]:
# Method 2

a = np.random.randint(10, size= (2,3,5))
print(a)


[[[6 1 0 4 7]
  [7 5 2 6 7]
  [0 1 7 7 3]]

 [[1 4 9 8 6]
  [3 4 5 9 0]
  [3 7 8 9 7]]]


In [19]:
# Method 3

a = np.random.rand(2,3,5)
print(a)


[[[0.10059645 0.40095148 0.40997973 0.30119783 0.82650555]
  [0.46574529 0.44648288 0.93802354 0.71669959 0.59371512]
  [0.78091488 0.75637248 0.22724756 0.83845131 0.58184508]]

 [[0.16076903 0.17563192 0.87767326 0.73093584 0.00874069]
  [0.14316787 0.70872037 0.62742778 0.23906137 0.72579579]
  [0.73765692 0.5241309  0.02827197 0.43650616 0.48301642]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [20]:
# your code here

b = np.ones((5,3,2))
print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


#### 6. Print *b*.


In [10]:
# your code here

print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [11]:
# your code here

a.shape == b.shape


False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [12]:
# your answer here

# c = a + b
# Não é possível adicionar dois shapes de tamanhos diferentes.

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [21]:
# your code here

c = b.transpose()
print(c.shape, a.shape)
print(c)


(2, 3, 5) (2, 3, 5)
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [22]:
# your code/answer here

d = a + c
print(d)
# Because is some shape


[[[1.10059645 1.40095148 1.40997973 1.30119783 1.82650555]
  [1.46574529 1.44648288 1.93802354 1.71669959 1.59371512]
  [1.78091488 1.75637248 1.22724756 1.83845131 1.58184508]]

 [[1.16076903 1.17563192 1.87767326 1.73093584 1.00874069]
  [1.14316787 1.70872037 1.62742778 1.23906137 1.72579579]
  [1.73765692 1.5241309  1.02827197 1.43650616 1.48301642]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [23]:
# your code/answer here

print(a)

print ("separacao")
print(d)

# Array add 1. for element in a

[[[0.10059645 0.40095148 0.40997973 0.30119783 0.82650555]
  [0.46574529 0.44648288 0.93802354 0.71669959 0.59371512]
  [0.78091488 0.75637248 0.22724756 0.83845131 0.58184508]]

 [[0.16076903 0.17563192 0.87767326 0.73093584 0.00874069]
  [0.14316787 0.70872037 0.62742778 0.23906137 0.72579579]
  [0.73765692 0.5241309  0.02827197 0.43650616 0.48301642]]]
separacao
[[[1.10059645 1.40095148 1.40997973 1.30119783 1.82650555]
  [1.46574529 1.44648288 1.93802354 1.71669959 1.59371512]
  [1.78091488 1.75637248 1.22724756 1.83845131 1.58184508]]

 [[1.16076903 1.17563192 1.87767326 1.73093584 1.00874069]
  [1.14316787 1.70872037 1.62742778 1.23906137 1.72579579]
  [1.73765692 1.5241309  1.02827197 1.43650616 1.48301642]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [25]:
# your code here

e = a*c

print(e)

[[[0.10059645 0.40095148 0.40997973 0.30119783 0.82650555]
  [0.46574529 0.44648288 0.93802354 0.71669959 0.59371512]
  [0.78091488 0.75637248 0.22724756 0.83845131 0.58184508]]

 [[0.16076903 0.17563192 0.87767326 0.73093584 0.00874069]
  [0.14316787 0.70872037 0.62742778 0.23906137 0.72579579]
  [0.73765692 0.5241309  0.02827197 0.43650616 0.48301642]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [26]:
# your code/answer here

print(e)

print(a)



[[[0.10059645 0.40095148 0.40997973 0.30119783 0.82650555]
  [0.46574529 0.44648288 0.93802354 0.71669959 0.59371512]
  [0.78091488 0.75637248 0.22724756 0.83845131 0.58184508]]

 [[0.16076903 0.17563192 0.87767326 0.73093584 0.00874069]
  [0.14316787 0.70872037 0.62742778 0.23906137 0.72579579]
  [0.73765692 0.5241309  0.02827197 0.43650616 0.48301642]]]
[[[0.10059645 0.40095148 0.40997973 0.30119783 0.82650555]
  [0.46574529 0.44648288 0.93802354 0.71669959 0.59371512]
  [0.78091488 0.75637248 0.22724756 0.83845131 0.58184508]]

 [[0.16076903 0.17563192 0.87767326 0.73093584 0.00874069]
  [0.14316787 0.70872037 0.62742778 0.23906137 0.72579579]
  [0.73765692 0.5241309  0.02827197 0.43650616 0.48301642]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [30]:
# your code here


d_max = a.all(d)
d_min = min(d)
d_mean = mean(d)



ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [ ]:
# your code here

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [1]:
# your code here

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here